import React, { useState } from 'react'
import Main from '../component/Main'
import Header from '../component/Header'
import Footer from '../component/Footer'
import Head from 'next/head'
import Link from 'next/link'



export default function Home() {
 
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Main/>
      <Footer/>
      
    </div>
  )
}
